apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: quote-service
spec:
  template:
    metadata:
      autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - name: quote-service
          image: ghcr.io/azimbabu/quote-service
          ports:
            - containerPort: 9101
          resources:
            requests:
              cpu: '0.1'
              memory: '128Mi'
            limits:
              cpu: '2'
              memory: '512Mi'